### ISSUE TITLE
Add stratum

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#1]
I suggest to include in the todos a button to choose a column in the dataset which to be used as stratum to be passed to the argument 'stratum' in resampling functions.

**Comment by andrechalom** [comment]
OK, this looks interesting. I've just uploaded a new version of the app including a new tab for the statistic selection (it's still very crude, but I intend to use drop downs in this page to select the columns). The app is now able to reproduce the first two examples in the RRR vignette.

The "stratum column" should be selected in the same page, right?

**Comment by piklprado** [comment]
It seems you added strata for the statistic of interest. This is useful too (issue #2), but the `stratum` argument is to run randomizations restricted to each stratum level. See linear regression examples (RRRR vignette) and similar argument `strata` in boot function from the boot package.

**Comment by andrechalom** [comment]
Working on it ;)

**Comment by andrechalom** [comment]
Live. See, for example, that the "Mean difference between groups" using the same column as categorical value and strata returns a constant distribution.
