### ISSUE TITLE
Cell randomization animations

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling-shiny#12]
> Please, please, please, we need an interface that shows the wonderful randomization of cells

(adapted from Mortara, S.)

**Comment by andrechalom** [comment]
Some suggestions of implementation, sent by adalardo:
http://www.nodeclipse.org/2013/08/20/JavaScript-Spreadsheet-Datagrid.html

**Comment by adalardo** [comment]
Veja isso, tem simulação em planilha:
http://mleibman.github.io/SlickGrid/examples/example14-highlighting.html

**Comment by ayanamartins** [comment]
I made a first attempt in these animations by adding a "Tutorials" tab that has an example with the rhyzophora data set. My goal was to create an environment where the resampling procedure could be understood step by step. 
Here it is: https://github.com/ayanamartins/Rsampling-shiny

**Comment by andrechalom** [comment]
Well, that's a really nice take on how to handle this issue. I have shown the animated graph to some other people and everyone agrees that this is a very didactic way of "building" the distribution.

I have, however, some suggestions about what should be done before this is incorporated in the main repository.
- Well, first we need to develop the help texts ;) Not only they should explain the dataset, but also the function that's being applied and the hypothesis that's being tested.
- I don't think we need to display the original data set at every step. We could show the original data set before anything is run (and the histogram is clear), and show the modified data set after each step. Every time the user presses the "Clear" button, we show the original data set again. Also, the modified table is displaying some lines in blue, and for a moment I thought that the lines in blue were being randomized. Maybe we can make the cells that are being resampled stand out (blue background?)
- Also, maybe we could use the same graph for the original (in black) and the current randomization (in blue)? I think that could save some space in the interface, but let me know if this is too cluttered.

Also, running from `runGithub("ayanamartins/Rsampling-shiny")`, I noticed that the interface is crashing with

``` R
Error in is.data.frame(data) : object 'rhyzophora' not found
```

That's because the package Rsampling is not loaded by the interface at the startup, but only when the "Install package" tab is rendered. That is fixed by calling "library(Rsampling)" from the commandline, before running the app. I'll fix this and send a pull request to your fork.

**Comment by ayanamartins** [comment]
Great! I agree with most of your suggestions. Some of them are actually the reason why I haven't send a pull request.

However, I think that it mat be important to keep the original data set visible in the tutorial. By comparing the original and the randomized sets a few times, it may be easier to understand the different types of randomizations.

**Comment by andrechalom** [comment]
On the other hand, I believe that comparing the datasets between randomizations is easier to see what's changed. In the rhyzophora example, I kept pressing "Do it again" while looking at the randomized table to convince myself that only the second column was changing between one randomization and the other ;)

**Comment by piklprado** [comment]
Amazing how you summarized the basic idea so nicely, @ayanamartins ! Great resource to teach significance tests using randomizations, as [Julian Simon](http://www.juliansimon.com/writings/Resampling_Statistics/) proposed. I think this can turn into an interactive book by The Spherical Chicken team. In doing that we will have separate projects for the engine, the interface and the companion teaching resource. Guesses?

**Comment by ayanamartins** [comment]
Interactive book! <3 <3

**Comment by piklprado** [comment]
If we do so, we keep in the shiny interface only help tabs and more traditional tutorials/vignettes showing how to use the interface step by step.

**Comment by andrechalom** [comment]
Interactive book! <3 <3 [2]

**Comment by adalardo** [comment]
Dear all, 

sorry, I missed the discussion... I was concentrated in finished a animated version of the SOI's (statistic of interest) graphic. The logic behind is a little trick ...
What Ayana have made is really impressive and I believe it  is possible to use the same logic to run the animated in the Tutorial... Please take a look at:

library(shiny)
runGitHub("Rsampling-shiny", "adalardo", ref="animated")

and click in UPDATE GRAPHIC in RESAMPLING tab

I am sorry if this is in another direction, I missed the discussion! The animation gives a lot of work...

**Comment by andrechalom** [comment]
Merged the tutorials and animations and releasing a new version [v1.3](https://github.com/andrechalom/Rsampling-shiny/releases/tag/v1.3). Thank you all so much for the amazing job!

I think we still need to decide if we want to expand the tutorials inside the interface, or start working on an interactive book.
