### ISSUE TITLE
Option for one-tailed tests

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#13]
In the summary of the randomization, can we include an option for one-tailed test? Currently all tests are two-tailed.

**Comment by andrechalom** [comment]
Will work on that.

**Comment by andrechalom** [comment]
Added that option. I'm a bit confused about the "right"/"left"/"greater"/"lesser" nomenclature for hypothesis tests, please check if what the package is doing is the right thing (if it's not, we have one task left!)

**Comment by piklprado** [comment]
Working beautifully! The nomenclature greater/lesser/two-sided seems clear to me. I would only change the title of this option to "Alternative hypothesis".  Match perfectly with my #14  to add accepatnce region to the plots.
