### ISSUE TITLE
Statistic does not update

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#17]
In the build 1.2 the statistic values does not update when I change the variables. But it does if I change the statistics. The same with Rsampling-shiny  ran with `runGitHub(repo="andrechalom/Rsampling-shiny")` and with Rsampling installed with `install_github("lageIBUSP/Rsampling", ref="noplyr")`

**Comment by andrechalom** [comment]
Oops, that was me trying to isolate the custom f(). I guess I'll have to make some better code for checking these things later, but for now I'll submit a version with a ugly code that runs (tidying up here means tidying up #10 as well)
