### ISSUE TITLE
some suggestions of statistics of interest

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#2]
Most of the basic problems need one of these statistics of interest:
- Differences between means of columns, rows or stratum levels
- Mean or variance of single column, a single row or a single stratum level
- Mean of sums of rows, columns, or stratum levels
- Mean of differences between two columns (paired differences)
- F statistics-like: ratio of variances or Sum of squares within columns, rows or starum levels to total variance or total SS
- Intercept and slope of regression of one column x other column (entire columns of subset by stratum levels)

**Comment by andrechalom** [comment]
Status:
- _Mean or variance of single column, a single row or a single stratum level_: Single column mean & single column sd implemented (for single row and single stratum, it's easy to convert the input file)
- _Differences between means of columns, rows or stratum levels_: Difference between the means of stratum is implemented as "mean difference between groups", but without the "stratum" option being used as a restriction to the randomization per se. I can add other options as "mean difference between columns" (not pairwise), but I think this may be a little confusing with the pairwise difference. Also, this can be simulated with small edits to the input file, converting the two columns in one and adding a category column.
- _Mean of sums of rows, columns, or stratum levels_: implemented mean of sum of row/cols, but it's throwing "Error in eval(expr, envir, enclos) : object 'rn' not found" in the peucetia example (it works on the azteca dataframe, however, so it may be a type problem with booleans??)
- _Mean of differences between two columns (paired differences)_: implemented as "mean difference between columns", updated the in-app explanation
- _F statistics-like: ratio of variances or Sum of squares within columns, rows or starum levels to total variance or total SS_: TO DO.
- _Intercept and slope of regression of one column x other column_: Added intercept, slope and correlation between two columns.

**Comment by piklprado** [comment]
Great! One more: differences in slopes of linear regressions applied to different levels of a factor.

**Comment by piklprado** [comment]
I suggest to give high priority to F-statistic or alike, as comparison among more than two groups is a pretty common problem that certainly will show up during the Eco Escola.

**Comment by andrechalom** [comment]
After thinking about the only other statistic suggested here, (differences in slopes of linear regressions applied to different levels of a factor), I've decided to include it as "help" in the custom statistic selector. The code there is the same as in the vignette.
