### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by ayanamartins** [lageIBUSP/Rsampling-shiny#20]
The interface should be translated to Portuguese. Maybe:
http://www.r-bloggers.com/another-take-on-building-a-multi-lingual-shiny-app/

**Comment by andrechalom** [comment]
OHNO, the blog post you referenced uses plyr! :crying_cat_face: 

The link inside that post is broken, but the original blog post can be seen [here](http://www.r-bloggers.com/design-a-bilingual-shiny-application/), I think we can use something like this. We will probably need to write a csv with the translated texts, as we have long texts in the interface.

**Comment by ayanamartins** [comment]
I have started working on the translation following the post andrechalom suggested. However, as it is, an individual output (for example, `<output$text1>`) is required for each piece of text in the interface. D:

Does anyone have a better idea? 

Here it is (look at the data input tab):

``` R
library(shiny)
runGitHub("Rsampling-shiny", "ayanamartins", ref="multilingual")
```

**Comment by andrechalom** [comment]
Can't we use "translate" in the interface? This way, we don't have to create lots of objects in server.R.
Also, the "selected" option (ui.R, line 10) should be the value, and not the label (i.e., "en"). 

In your current branch the labels are not being displayed until the first "resampling" is finished, but I intended to fix this in the master branch still today.

**Comment by ayanamartins** [comment]
"Can't we use "translate" in the interface?" -- <cite>@andrechalom</cite>

I still don't know how to that... If I define the "translate" function in the interface, I don't know how to pass the input information (in this case, the language chosen by the user) to it.

**Comment by andrechalom** [comment]
I think input$ and output$ objects are available on the interface as well, aren't they?

**Comment by ayanamartins** [comment]
I don't think so (however Shiny scoping rules are not so clear to me at this point)...

I also tried saving the input as global variable, however in this cases there is nothing informing the app that it must be re-rendered.

A possible solution could be something along these lines: 
http://shiny.rstudio.com/gallery/dynamic-ui.html

**Comment by andrechalom** [comment]
Hmmmm, I don't see how a renderUI could be used to reduce the number of objects that need to be created in the server-side... This seems to be a harder problem than I had anticipated

**Comment by ayanamartins** [comment]
In fact... It would just reduce the length of the code in the interface.

Should we create a parallel version in Portuguese for now?

**Comment by andrechalom** [comment]
Maybe that's the best thing to do for now. I'll try to come up with
something tomorrow, but I'm not very confident =/

**Comment by ayanamartins** [comment]
I am currently working on a version in which the language is defined as a global variable and must be set before the app is started. The translation is not finished yet.

``` R
library(shiny)
language <- "pt"
runGitHub("Rsampling-shiny", "ayanamartins", ref="multilingual")
```

**Comment by andrechalom** [comment]
OK, now that's a very intelligent take on the issue.

Maybe we can add later a button that "resets" the app to change the
language.

On Sat, Jul 18, 2015 at 11:33 PM, Ayana B. Martins <notifications@github.com

**Comment by andrechalom** [comment]
Hi, how are we progressing on this issue? I can work on this starting
next monday, but I'd like to make sure we're not duplicating efforts.

**Comment by ayanamartins** [comment]
We are translating [WIP] the interface following the strategy that I mentioned before. Check:

``` R
library(shiny)
language <- "pt"
runGitHub("Rsampling-shiny", "ayanamartins", ref="multilingual")
```

**Comment by andrechalom** [comment]
Ah, all right. 

I got a bit confused because I accidentaly created a "multilingual" branch on my fork, and andrechalom/multilingual is not being updated. Sorry for the confusion! :relieved:
