### ISSUE TITLE
Show the whole data frame in 'Data Input' tab

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#23]
Many students in the field course suggested that the 'Data Input' tab should show the entire data set, not only the first 15 rows. The simplest thing we can do is to show a table with all rows. If the table is long, the user can scroll down the browser window. If the user wants only a glimpse of the first rows, he/she will not scroll. Simple as that. I would use this before trying more sophisticated solutions.

**Comment by andrechalom** [comment]
Done. As it is such a small change, I've simply pushed it to the main repository.

My idea for displaying the first columns was related to displaying the animations on these columns, but as we're working on the Tutorial tab with another approach, this is just not necessary anymore.
