### ISSUE TITLE
Progress bar appearing on the "Data input" and "Rsampling" (intro) tabs 

### ISSUE THREAD

**Issue by ayanamartins** [lageIBUSP/Rsampling-shiny#29]
Should it be there?

![bug_progress](https://cloud.githubusercontent.com/assets/11555881/8638787/06f5b1d8-289c-11e5-94fb-1384e9128e98.png)

**Comment by andrechalom** [comment]
The progress bar is displayed every time the sampling is done. It can be triggered by changing the input data or the statistics. Changing options on the "Resampling" page do not change the sampled distribution, so it only displays a new graph and the progress bar when the user clicks "update graph".

This way, I don't think "should the progress bar be there" is the right question. The progress bar should be displayed whenever the resampling is done. What may be in question is "should the resampling be done when the user changes the dataset or statistic?"

**Comment by adalardo** [comment]
I agree. This is the right question. For large data set, for example, will be better do the resampling after clicking the "update graph". In this case we should change the name for "run sampling" or something like it...

**Comment by andrechalom** [comment]
Trying to fix this, but when I try to change the way things are calculated, suddenly run_iter() starts to crash with "non-numerical argument for mathematical function".

I really don't understand the code for the generation of the animated graph. What does session$clientData$url_search$auto does? Is it browser-dependent? Why are we checking that value?
