### ISSUE TITLE
upload file data input tab

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/Rsampling-shiny#30]
I tested the new version and the "upload file" option is not working since the last changes

**Comment by andrechalom** [comment]
I'm starting to think that we should automate testing for the upload file tab, as EVERYTIME we change stuff in this code the upload tab breaks down =/

**Comment by ayanamartins** [comment]
Here it seems to be working (at least for the file I tried...)

**Comment by piklprado** [comment]
Not working with me too. Session information:

``` r
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=pt_BR.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] gridExtra_0.9.1   Rsampling_0.0.0.3 shinyBS_0.61      shiny_0.12.1     

loaded via a namespace (and not attached):
 [1] compiler_3.2.0  R6_2.1.0        htmltools_0.2.6 tools_3.2.0    
 [5] Rcpp_0.11.6     jsonlite_0.9.16 digest_0.6.8    xtable_1.7-4   
 [9] httpuv_1.3.2    mime_0.3        tcltk_3.2.0    
```

**Comment by adalardo** [comment]
Another thought! Since the examples are used in tutorial tab, we can remove them from  "input data" tab and keep it for upload files only.

**Comment by ayanamartins** [comment]
I would keep them anyway. My idea was to ask the students to re-run the exercise to find the p-value in the Resampling tab. That is why I didn't add multiple randomizations and p-value calculation in the Tutorial tab.

**Comment by adalardo** [comment]
OK! Makes sense.

**Comment by piklprado** [comment]
I still think that Ayana's 'tutorials' are more akin to lessons or hands-ons to learn the basic concepts and operations, and they are doing great in this sense. But this leaves the question: do we need 'classical' tutorials that show step by step how to use the interface?

**Comment by adalardo** [comment]
Maybe not like EcoVirtual, but I like the idea to have a brief tutorial for guidance associated with a documentation (links) about the concepts  that the exercices work with. We could think about two levels of guidance, for students who wants to learn by himself and to teacher who will use the Rsampling to teach basic concepts in statistics.

**Comment by andrechalom** [comment]
I'll try to fix the issue with the upload tab.

On the other discussion going on: I agree with @piklprado that the tutorials are more aligned with the idea of a learning resource on randomization (such as an interactive book) than with a tutorial on how to use the interface. What do you think about separating the tutorials to a new project and creating links from one to the other?

There is one clear advantage here: the calculations done by the tutorial are much more lightweight (as each "click" runs only one randomization, instead of 10000), and don't use any user input, so we could host the tutorial on a webserver (lage? ecovirtual?) instead of requiring the user to have R locally installed.

**Comment by andrechalom** [comment]
OK, after some hours of trial and error I think I mostly understand the code. Submitted PR #35, please give feedback.

**Comment by adalardo** [comment]
Works like a charm! It is  working  in the "isolate" branch. You should merge changes to master! I think is better  work on a fully working version than waiting for more test!
