### ISSUE TITLE
Improvements to the tutorial design

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling-shiny#33]
I have shown the tutorials to some users with experience in design and web usability, and they gave the following feedback:
- the background color for the tables is too dark (both the gray and the blue should be lighter);
- the interface is too cluttered. Maybe there could be a button that shows the original data when held down, and the resampled data otherwise?
- the blue text above the blue histogram seems to be a legend for the histogram, while the histogram legend is in a position and color that's not prominent. Also, it reads "left" when it should be "right". Maybe the histogram legend should be moved up or made blue, and the text describing the other graphs should be placed near those graphs;
- The "original data" and "randomized data" tables should have a title;
- the organization into "Question" and "Hypothesis" is great :smile_cat:;
- there could be a "loop" button that makes a new randomization every 5 seconds?
- the randomized data should highlight what's changing. Maybe only the columns that change should have a blue background.
- in the Ants tutorial, it should be more clear that the question "How should... experimental design?" is not answerable in the interface, as the user cannot change the randomization scheme. Also, the hypothesis reads "Damage on young leaves will lead to **more** recruited ants when compared to damage on old leaves", but the graphs show "Damage on old leaves will lead to **less** recruited ants when compared to damage on young leaves"

**Comment by ayanamartins** [comment]
These a great suggestions!

**Comment by adalardo** [comment]
I like the suggestions too!
