### ISSUE TITLE
The checkbox "show rejection region" higlights the acceptance region

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#44]
Some students got confused with the meaning of rejection region because the option in Rsampling is to show this, but it is the accepatnce regions that is highlighted. PR #45 changes the text of the checkbox. An alternative is to change what is highlighted.

**Comment by andrechalom** [comment]
That's absolutely correct. That's something that bothered me when we first implemented it, but I forgot to change it at the time.
