### ISSUE TITLE
Ancova

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#46]
A much needed enhancement is to include ANCOVA in the interface. For this we need two new statistics:

1 - Difference between slopes of regressions fitted to two groups 
2 - Difference between intercepts of regressions fitted to two groups, with a common slope (which is the slope of a regression fitted to the whole data set). 

For both we'll need the fields dependent variable, independent variable and categorical variable.

**Comment by andrechalom** [comment]
Implemented both functions.
- [x] To-do: we need help texts on these functions (file lang.csv)
- [x] To-do: we need to decide which columns are randomized in these. Currently, we have dependent and independent being randomized.
- [x] Needs to check: for both statistics, it is common to see one selection of dependent and independent variables producing non-significant results, but the reverse is highly significant. For example, ancova1 with root ~ canopy trunk, with soil instability being used as categorical, is giving non-significant; while canopy ~ root is highly significant.

**Comment by andrechalom** [comment]
It's kind of strange that root ~ canopy trunk, with soil instability being used as categorical, is giving non-significant; while canopy ~ root is highly significant.

**Comment by piklprado** [comment]
2nd todo: I think the right choice is randomize the categorical variable, or xy pairs (rows as units). Makes sense?

3rd todo: let's check that with standard anova in R. It is possible, but sounds a little weird. But as p values sometimes give weird results... Just a guess: roots is a count variable with narrow range, so to use it as dependent or independent can change the test results a lot
