### ISSUE TITLE
Lock meaningless randomization types for pre-defined statistics

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#47]
For the statistics 
-  Mean difference between groups
- Variance ratio for more than two groups
- Regression intercept
- Regression coeficient
- Correlation between columns

Only radomization within columns makes sense, but this choice causes an error. I understand that internally these statistics leads to selection of a single column to be resampled by the normal method. But I think that is easier to the user to think that randomization is carried over columns, as the help text says that in normal randomization all values are shuffled. The most laborious solution is to rewrite randomization to be carried out by within_columns. An alternative would be change the help text about normal shuffling (maybe contingent to the statistics chosen?).

In any case we need to lock randomization types that are meaningless for each standard statistics.

**Comment by andrechalom** [comment]
OK, the standard statistics are:
- Mean difference between columns
- Mean difference between 2 groups
- Column mean
- Column standard deviation
- F statistic
- Mean sum of rows
- Mean sum of columns
- Regression intercept
- Regression coefficient
- Correlation between columns
- Difference between slopes of regressions fitted to two groups (ANCOVA-1)
- Difference between intercepts of regressions fitted to two groups, with a common slope (which is the slope of a regression fitted to the whole data set).  (ANCOVA-2)

Exactly which randomization schemes are meaningful for each of these statistics?

**Comment by piklprado** [comment]
I think we should lock to within columns randomization the cases that have a grouping variable:
- Mean difference between 2 groups
- F statistic 
- Regression intercept
- Regression coefficient
- Correlation between columns
- Difference between slopes of regressions fitted to two groups (ANCOVA-1)
- Difference between intercepts of regressions fitted to two groups, with a common slope (which is the slope of a regression fitted to the whole data set).  (ANCOVA-2)

**Comment by andrechalom** [comment]
Added simple column mean and sd, as most rand types are also meaningless for those
