### ISSUE TITLE
Fix bugs in at least one browser and selected OS'

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling-shiny#48]
We still have some bugs concerning appearance  mostly in tutorials (e.g. #41, #42) and a few functionalities (e.g. #43). Some of them have also reproducibility issues too. My guess is that the many combinations of OS' and browsers types/versions are making things hard to solve.

But we need to assure that the interface works smoothly at least in a browser (firefox?) and one selected version of each OS used by our students (say windows 8 for Microsoft, Yosemite for Mac; and any Linux, because probably Linux is not a problem but check).

**Comment by andrechalom** [comment]
41 is unfixable as long as I've not been able to reproduce it a single time. As it might be related to older software, such as Windows XP or outdated browsers, I really recommend updating the operation systems and browsers.

42 is fixed on PR #49 

43 was apparently fixed on shiny, on some of the versions between 2015 and now. I am able to select the same file again in Firefox (tested on Windows), and the displayed data below confirms that it has changed. However, it is not fixed on Chrome.
