### ISSUE TITLE
Trocar p = 0

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling-shiny#59]
Se nenhuma simulação é mais extrema do que o observado, p está sendo reportado como zero. Na verdade é p < 1/(n obs)

**Comment by saramortara** [comment]
o p continua sendo reportado como zero no caso de nenhuma simulação ser mais extrema do que o observado

**Comment by adalardo** [comment]
Alguns autores advogam que é uma boa prática incluir o valor observado
entre os pseudo-valores gerados pela simulação. Isso, baseado em dois
pontos:
1. A amostra observada é uma das  configurações possíveis na premiação
2. O valor de p calculado é mais preciso e conservativo.

Em Qua, 18 de abr de 2018 09:05, saramortara <notifications@github.com>
escreveu:

**Comment by andrechalom** [comment]
Caros,

Bom ver que ainda existe interesse no Rsampling!

Pelo que eu estou entendendo da sugestão do Ale, a ideia é incluir o valor
observado como a primeira "simulação"? Isso faria com que o p calculado
fosse p = 1 / (n obs) diretamente; enquanto a observação original, que tem
um p menos "conservativo", seria apenas indicar na interface p < 1 / (n
obs). Então as opções são:

(1) alterar a interface para indicar p < 1 / (n obs) no caso de nenhuma
observação ser mais extrema ou
(2) alterar o código do Rsampling para incluir a observação como a primeira
"simulação"; essa opção não precisa de alterações na interface

Como vocês encaram essas alternativas em termos da didática? Eu acho mais
simples explicar as simulações como sendo apenas simulações, tenho um pouco
de receio que incluir o dado observado como uma simulação vá causar muita
confusão nos usuários.

Abs

**Comment by vrios** [comment]
Creio que a primeira opção é mais didática, pois embora as simulações sejam feitas com base nas observações, e a configuração original seja uma das possíveis de se obter nas simulações, ainda assim ela é teoricamente fruto de uma coleta de dados. Isso me parece que a torna conceitualmente separada das simulações, mesmo que as simulações sejam embaralhamento dos dados originais.

**Comment by adalardo** [comment]
Eu fico contente com a solução p< 1/nsim. Acho bem razoável! De fato me
parece uma solução melhor que p= ( 1+ número de simulações < = observado)/
nsim. É uma solucao até mais precisa sem deixar de ser conservativa.

Em Qui, 19 de abr de 2018 19:04, Vitor Rios <notifications@github.com>
escreveu:
