### ISSUE TITLE
Allow custom f() to return vector

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling-shiny#7]
Currently, the interface only works for a single return value of the statistic of interest. Rsampling, however, is able to accept vector-valued functions and return a matrix of distributions. Can we update the interface to support these as well?

**Comment by piklprado** [comment]
I think it depends on what we intend with the shiny interface. There is a trade-off between including all functionalities of the engine in the GUI x keeping it simple. If we choose the later, allowing f() return more than one value seems too advanced to include in the interface.

**Comment by andrechalom** [comment]
OK, if this is not required for the field course, I'm voting for not including it.

**Comment by andrechalom** [comment]
PS, added some checks for multivalued f() on the dev branch
